version: "3"

networks:
  cocoannotator:
    external: false

services:
  webserver:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: annotator_webclient
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SECRET_KEY=RandomSecretKeyHere
      - FILE_WATCHER=true
      - NAME=Test Annotator
      - GOOGLE_APPLICATION_CREDENTIALS=/juroujin-sandbox-f1eeaadf8ed6.json
      - MASK_RCNN_FILE=/models/mask_rcnn_coco.h5
      - |
        MASK_RCNN_CLASSES=
        BG,person,bicycle,car,motorcycle,airplane,
        bus,train,truck,boat,traffic light,
        fire hydrant,stop sign,parking meter,bench,bird,
        cat,dog,horse,sheep,cow,elephant,bear,
        zebra,giraffe,backpack,umbrella,handbag,tie,
        suitcase,frisbee,skis,snowboard,sports ball,
        kite,baseball bat,baseball glove,skateboard,
        surfboard,tennis racket,bottle,wine glass,cup,
        fork,knife,spoon,bowl,banana',apple,
        sandwich,orange,broccoli,carrot,hot dog,pizza,
        donut,cake,chair,couch,potted plant,bed,
        dining table,toilet,tv,laptop,mouse,remote,
        keyboard,cell phone,microwave,oven,toaster,
        sink,refrigerator,book,clock,vase,scissors,
        teddy bear,hair drier,toothbrush
    volumes:
      - "./datasets:/datasets"
      - "./models:/models"
      - "./juroujin-sandbox-f1eeaadf8ed6.json:/juroujin-sandbox-f1eeaadf8ed6.json"
    depends_on:
      - workers
    networks:
      - cocoannotator
  workers:
    container_name: annotator_workers
    build:
      context: .
      dockerfile: ./backend/workers/Dockerfile
    volumes:
      - "./backend/config:/workspace/config"
      - "./backend/webserver:/workspace/webserver"
      - "./backend/workers:/workspace/workers"
      - "./backend/database:/workspace/database"
      - "./datasets:/datasets"
    depends_on:
      - messageq
    ports:
      - 5555:5555
    networks:
      - cocoannotator
  messageq:
    image: rabbitmq:3
    container_name: annotator_message_q
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 5672:5672
    networks:
      - cocoannotator
